# Generated by Django 5.0.1 on 2024-01-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendWise_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
