# Generated by Django 5.0.1 on 2024-01-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendWise_app', '0002_expense_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.FloatField(null=True),
        ),
    ]
