# Generated by Django 5.0.1 on 2024-01-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpendWise_app', '0003_alter_expense_amount_alter_expense_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
